#!/bin/bash
#
# Builds newsmanapp.zip for uploading as a GitHub release.
# Users install/upgrade the WordPress plugin by uploading this archive
# via WordPress Admin > Plugins > Add New > Upload Plugin.
#
# Steps:
#   1. Copies the plugin directory to a temporary location
#   2. Removes dot-directories (.git, .claude, etc.) and dot-files
#   3. Removes the tools/ directory
#   4. Deletes vendor/ and composer.lock, runs composer install --no-dev
#   5. Removes composer.lock generated by composer install
#   6. Cleans non-runtime files from vendor packages
#   7. Creates the zip archive with newsmanapp/ as root directory
#
# Usage:
#   ./build-release-zip.sh <plugin_dir> <php_binary> <composer_path> <output_zip>
#
# Example:
#   ./build-release-zip.sh /path/to/plugins/newsmanapp php8.2 /usr/local/bin/composer /a release dir/newsmanapp.zip

set -e

if [ $# -ne 4 ]; then
    echo "Usage: $0 <plugin_dir> <php_binary> <composer_path> <output_zip>"
    echo "  plugin_dir     — path to the newsmanapp plugin directory"
    echo "  php_binary     — PHP binary to use (e.g. php8.2)"
    echo "  composer_path  — path to the Composer binary (e.g. /usr/local/bin/composer)"
    echo "  output_zip     — output path for the .zip archive"
    exit 1
fi

PLUGIN_DIR="$(realpath "$1")"
PHP_BIN="$2"
COMPOSER_PATH="$3"
OUTPUT_ZIP="$4"

if [ ! -d "$PLUGIN_DIR" ]; then
    echo "Error: $PLUGIN_DIR does not exist."
    exit 1
fi

if [ ! -f "$PLUGIN_DIR/newsmanapp.php" ]; then
    echo "Error: $PLUGIN_DIR/newsmanapp.php not found. Is this the correct plugin directory?"
    exit 1
fi

if [ ! -f "$PLUGIN_DIR/composer.json" ]; then
    echo "Error: $PLUGIN_DIR/composer.json not found."
    exit 1
fi

# Resolve output path to absolute.
case "$OUTPUT_ZIP" in
    /*) ;;
    *) OUTPUT_ZIP="$(pwd)/$OUTPUT_ZIP" ;;
esac

echo "Plugin dir  : $PLUGIN_DIR"
echo "PHP binary  : $PHP_BIN"
echo "Composer    : $COMPOSER_PATH"
echo "Output      : $OUTPUT_ZIP"
echo ""

# Step 1: Copy plugin to a temp directory.
echo "=== Step 1: Copying plugin to temporary directory ==="
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

cp -a "$PLUGIN_DIR" "$TEMP_DIR/newsmanapp"
WORK_DIR="$TEMP_DIR/newsmanapp"
echo "Copied to: $WORK_DIR"
echo ""

# Step 2: Remove dot-directories and dot-files.
echo "=== Step 2: Removing dot-directories and dot-files ==="
find "$WORK_DIR" -mindepth 1 -name '.*' | while read -r entry; do
    rm -rf "$entry"
    echo "Removed: $entry"
done
echo ""

# Step 3: Remove the tools/ directory.
echo "=== Step 3: Removing tools/ directory ==="
if [ -d "$WORK_DIR/tools" ]; then
    rm -rf "$WORK_DIR/tools"
    echo "Removed: $WORK_DIR/tools"
fi
echo ""

# Step 4: Delete vendor/ and composer.lock, run composer install --no-dev.
echo "=== Step 4: Cleaning vendor and running composer install --no-dev ==="
if [ -d "$WORK_DIR/vendor" ]; then
    rm -rf "$WORK_DIR/vendor"
    echo "Deleted: $WORK_DIR/vendor"
fi
if [ -f "$WORK_DIR/composer.lock" ]; then
    rm "$WORK_DIR/composer.lock"
    echo "Deleted: $WORK_DIR/composer.lock"
fi

cd "$WORK_DIR"
"$PHP_BIN" "$COMPOSER_PATH" install --no-dev -vvv
echo ""

# Step 5: Delete composer.lock generated by composer install.
echo "=== Step 5: Removing composer.lock ==="
if [ -f "$WORK_DIR/composer.lock" ]; then
    rm "$WORK_DIR/composer.lock"
    echo "Deleted: $WORK_DIR/composer.lock"
fi
echo ""

# Step 6: Clean non-runtime files from vendor packages.
echo "=== Step 6: Cleaning non-runtime files from vendor ==="
VENDOR_DIR="$WORK_DIR/vendor"

# Remove known non-runtime directories.
for dir in tests test examples example libs wiki doc docs .github .settings; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type d -name "$dir" | while read -r d; do
        rm -rf "$d"
        echo "Removed: $d"
    done
done

# Remove non-runtime files from package roots.
for pattern in phpunit.xml phpunit.xml.dist phpunit.xml.dist.bak .travis.yml .gitignore .gitattributes .gitmodules .buildpath .project .eclipse-PHP-formatter.xml runtest.sh README.md CHANGELOG.md CONTRIBUTING.md; do
    find "$VENDOR_DIR" -mindepth 2 -maxdepth 3 -type f -name "$pattern" | while read -r f; do
        rm "$f"
        echo "Removed: $f"
    done
done
echo ""

# Step 7: Create the zip archive.
echo "=== Step 7: Creating zip archive ==="
[ -f "$OUTPUT_ZIP" ] && rm "$OUTPUT_ZIP"

cd "$TEMP_DIR"
zip -r "$OUTPUT_ZIP" newsmanapp/

echo ""
echo "=== Done ==="
echo "Archive created: $OUTPUT_ZIP"
echo "Size: $(du -h "$OUTPUT_ZIP" | cut -f1)"
